# Generated by Django 5.1.15 on 2026-06-27 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nur zur Unterscheidung, z. B. „Meine Firma“.', max_length=120, verbose_name='Profilname')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße & Hausnr.')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ort')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Land')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Telefon')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='BIC')),
                ('tax_number', models.CharField(blank=True, max_length=60, verbose_name='Steuernummer')),
                ('vat_id', models.CharField(blank=True, max_length=40, verbose_name='USt-IdNr.')),
                ('register_court', models.CharField(blank=True, max_length=120, verbose_name='Registergericht')),
                ('register_number', models.CharField(blank=True, max_length=60, verbose_name='Registernummer')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standardprofil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
