# Generated by Django 5.1.15 on 2026-06-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='payment_terms',
            field=models.CharField(default='Zahlbar innerhalb von 14 Tagen ohne Abzug.', help_text='Steht unter der Summe, z. B. „Zahlbar innerhalb von 14 Tagen“.', max_length=300, verbose_name='Zahlungsbedingungen'),
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('description', models.CharField(max_length=300, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(default='Stk', max_length=30, verbose_name='Einheit')),
                ('unit_price_cents', models.PositiveIntegerField(verbose_name='Einzelpreis (Cent)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.19, help_text='Als Bruch, z. B. 0,19 für 19 %.', max_digits=4, verbose_name='USt-Satz')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
