# Generated by Django 5.1.15 on 2026-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_payment_terms_documentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Bis wann das Angebot gilt — erscheint unter den Positionen.', null=True, verbose_name='Gültig bis'),
        ),
    ]
