# Generated by Django 5.1.15 on 2026-06-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='party_a_label',
            field=models.CharField(default='Auftraggeber', help_text='Wie der Absender im Vertrag heißt, z. B. „Auftraggeber“.', max_length=80, verbose_name='Rolle Absender'),
        ),
        migrations.AddField(
            model_name='document',
            name='party_b_label',
            field=models.CharField(default='Auftragnehmer', help_text='Wie der Empfänger im Vertrag heißt, z. B. „Auftragnehmer“.', max_length=80, verbose_name='Rolle Empfänger'),
        ),
        migrations.CreateModel(
            name='DocumentClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('heading', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('body', models.TextField(verbose_name='Text')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.document')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
