# Generated by Django 5.1.15 on 2026-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_party_a_label_document_party_b_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='new_deadline',
            field=models.DateField(blank=True, help_text='Bis wann der offene Betrag nun gezahlt werden soll.', null=True, verbose_name='Neue Frist'),
        ),
        migrations.AddField(
            model_name='document',
            name='ref_amount_cents',
            field=models.PositiveIntegerField(default=0, verbose_name='Offener Betrag (Cent)'),
        ),
        migrations.AddField(
            model_name='document',
            name='ref_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rechnungsdatum'),
        ),
        migrations.AddField(
            model_name='document',
            name='ref_invoice_number',
            field=models.CharField(blank=True, help_text='Nummer der offenen Rechnung, an die erinnert wird.', max_length=60, verbose_name='Rechnungs-Nr.'),
        ),
        migrations.AddField(
            model_name='document',
            name='reminder_fee_cents',
            field=models.PositiveIntegerField(default=0, verbose_name='Mahngebühr (Cent)'),
        ),
        migrations.AddField(
            model_name='document',
            name='reminder_stage',
            field=models.CharField(choices=[('Zahlungserinnerung', 'Zahlungserinnerung'), ('1. Mahnung', '1. Mahnung'), ('2. Mahnung', '2. Mahnung'), ('3. Mahnung', '3. Mahnung')], default='Zahlungserinnerung', help_text='Von der freundlichen Erinnerung bis zur 3. Mahnung.', max_length=40, verbose_name='Stufe'),
        ),
    ]
